version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://dbuser:1234@db:5432/Task_manager_db
    volumes:
      - .:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8001 --reload

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Task_manager_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
