

services:
  fastapi_app:
    build:
      context: .
      target: dev  # dev stage for development
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:17
    container_name: postgres_db
    env_file: .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend_tests:
    build:
      context: .
      target: test
    volumes:
      - .:/app
    env_file: .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${TEST_DB_USER}:${TEST_DB_PASSWORD}@db:5432/${TEST_DB_NAME}
    command: pytest -v tests

volumes:
  pgdata:
