"""add ai fields to tasks

Revision ID: 4ca7d172a35b
Revises: 602077741270
Create Date: 2026-02-06 07:30:37.572703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca7d172a35b'
down_revision: Union[str, Sequence[str], None] = '602077741270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('ai_feedback', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('ai_recommendations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'ai_recommendations')
    op.drop_column('tasks', 'ai_feedback')
    # ### end Alembic commands ###
