"""add description to timelog

Revision ID: 602077741270
Revises: 2a16b4fe1aab
Create Date: 2026-01-16 19:14:00.852177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602077741270'
down_revision: Union[str, Sequence[str], None] = '2a16b4fe1aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('times', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('times', 'description')
    # ### end Alembic commands ###
