name: Run Tests in Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for DB to be healthy
        run: |
          for i in {1..10}; do
            if docker compose exec -T db pg_isready -U dbuser -d task_manager_db; then
              echo "Database is ready!"
              break
            fi
            echo "Waiting for DB..."
            sleep 5
          done

      - name: Run tests inside fastapi_app
        run: |
          docker compose exec -T fastapi_app pytest /app/tests -v

      - name: Shutdown
        if: always()
        run: docker compose down -v
