name: Backend Tests in Docker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # 👈 ensures we run docker-compose in backend/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Run tests inside fastapi_app
        run: docker compose exec -T fastapi_app pytest /app/tests-v

      - name: Shutdown containers
        if: always()
        run: docker compose down -v
