name: Backend Tests in Python

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: |
          docker build -t backend-test .

      - name: Run tests in container
        env:
          DATABASE_URL: "postgresql://user:pass@localhost:5432/testdb" # fake, not used
        run: |
          docker run --rm -e DATABASE_URL=$DATABASE_URL backend-test pytest tests -v
