name: CI/CD - Backend

on:
  push:
    branches: ["master"] # deploy only on master
  pull_request:
    branches: ["master"] # run tests on PRs

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend # adjust if backend lives in /backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests -v

  deploy:
    runs-on: ubuntu-latest
    needs: test # only run deploy if tests pass
    steps:
      - name: Trigger Render deploy
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
